FROM node:0.10.40-slim
MAINTAINER Damien Lebrun <dinoboff@hotmail.com>

COPY ["package.json", "bower.json", "/app/"]
WORKDIR /app

RUN apt-get update \
  && apt-get install -y vim git wget libfreetype6 libfontconfig bzip2 \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* \
  && npm install \
  && npm cache clear
